feat: added collapsible sidebar
Almanac-team/almanac pull request #63
Opened 2023-08-08 20:06 UTC by tfu2003

Created a collapsible sidebar. The open sidebar shows the icons and names and the closed only shows the icons. Currently, there is no delay for the transition so it may look choppy.

2023-08-09 07:12 UTC, hanmangokiwi requested changes

2023-08-09 07:12 UTC, hanmangokiwi commented on src/components/layout.tsx
> +        <Card className={`transition-all ${open ? "max-w-[20rem]" : "max-w-[6rem]"} p-4 shadow-blue-gray-900/5 transition-all duration-100 ease-in-out`}>
could we add the h-full back?

2023-08-09 08:08 UTC, tfu2003 commented on src/components/layout.tsx
> +        <Card className={`transition-all ${open ? "max-w-[20rem]" : "max-w-[6rem]"} p-4 shadow-blue-gray-900/5 transition-all duration-100 ease-in-out`}>
Added h-full back.

2023-08-09 20:15 UTC, tfu2003 commented on src/components/layout.tsx
> +                <hr className={`my-2 border-blue-gray-50 ${open ? "max-w-[20rem]" : "max-w-[3rem]"}`}/>
Made minimized sidebar slimmer. Something to note is that the icon may not be centered in the shadow when you hover over it. I fixed it by adjusting the widths, but I'm looking for a more permanent fix with centering items.

2023-08-10 07:44 UTC, hanmangokiwi requested changes

2023-08-10 07:44 UTC, hanmangokiwi commented on src/components/layout.tsx
> +                    {title}
can we do something like {open? title : null} instead?

2023-08-10 07:44 UTC, hanmangokiwi commented on src/components/layout.tsx
> +                    onClick={() => void router.push(`/${title.toLowerCase()}`)}
could we have a new prop instead of making the title lowercase?

2023-08-10 07:44 UTC, hanmangokiwi commented on src/components/layout.tsx
> +    state: boolean;
remove unused "state"

2023-08-10 07:44 UTC, hanmangokiwi commented on src/components/layout.tsx
> +                        state={open}
we already are using the StateContext provider, we don't need to pass in open to each component

2023-08-11 10:13 UTC, tfu2003 commented on src/components/layout.tsx
> +                <hr className={`my-2 border-blue-gray-50 ${open ? "max-w-[20rem]" : "max-w-[3rem]"}`}/>
Looks like this now.
<img width="70" alt="image" src="https://github.com/Almanac-team/almanac/assets/99298978/43e0efab-70fb-4c34-ac33-aee21c8f6679">

2023-08-11 20:13 UTC, tfu2003 commented on src/components/layout.tsx
> +                        state={open}
Removed.

2023-08-11 20:13 UTC, tfu2003 commented on src/components/layout.tsx
> +    state: boolean;
Removed.

2023-08-11 20:25 UTC, tfu2003 commented on src/components/layout.tsx
> +                    onClick={() => void router.push(`/${title.toLowerCase()}`)}
The title has to be lowercase to be able to redirect them to the appropriate page (localhost:3000/Track is different from localhost:3000/track). The actual title shown isn't changed on the sidebar. Even if it was a new prop, it'd still be the same code.

2023-08-11 20:37 UTC, tfu2003 commented on src/components/layout.tsx
> +                    {title}
Only thing I can think of is making a new component, which I did.

2023-08-11 20:46 UTC, tfu2003 commented on src/components/layout.tsx
> +                    className={open ? '' : 'hidden'}
Done. Although personally I don't think it looks more readable.

2023-08-12 08:01 UTC, hanmangokiwi approved these changes
LGTM!

2023-08-12 08:05 UTC, merged